FROM node:20-alpine

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev=false

COPY . .

ENV PORT=8080
EXPOSE 8080

CMD ["npm","run","dev","--","--host","0.0.0.0","--port","8080"]
