
-- P3.13.4 Search Quality Tuning
-- Typo tolerance, brand boosting, synonym expansion

-- 0) Tables
CREATE TABLE IF NOT EXISTS public.search_synonyms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alias text NOT NULL,
  canonical text NOT NULL,
  weight numeric(6,4) NOT NULL DEFAULT 0.0800,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (alias, canonical)
);

CREATE TABLE IF NOT EXISTS public.search_brand_aliases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alias text NOT NULL,
  boost numeric(6,4) NOT NULL DEFAULT 0.0800,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_brand_boost_range CHECK (boost >= 0 AND boost <= 0.3000)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_search_brand_aliases_alias_lower
  ON public.search_brand_aliases (lower(alias));

CREATE INDEX IF NOT EXISTS idx_search_synonyms_alias_lower
  ON public.search_synonyms (lower(alias)) WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_search_brand_aliases_active
  ON public.search_brand_aliases (is_active, lower(alias));

-- RLS
ALTER TABLE public.search_synonyms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.search_brand_aliases ENABLE ROW LEVEL SECURITY;

CREATE POLICY "synonyms_read" ON public.search_synonyms FOR SELECT USING (true);
CREATE POLICY "synonyms_admin" ON public.search_synonyms FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "brand_aliases_read" ON public.search_brand_aliases FOR SELECT USING (true);
CREATE POLICY "brand_aliases_admin" ON public.search_brand_aliases FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));

-- 1) Seed synonyms
INSERT INTO public.search_synonyms (alias, canonical, weight) VALUES
  ('موبايل', 'هاتف', 0.09),
  ('جوال', 'هاتف', 0.09),
  ('خلوي', 'هاتف', 0.09),
  ('لابتوب', 'حاسوب محمول', 0.08),
  ('لاب توب', 'حاسوب محمول', 0.08),
  ('هيدفون', 'سماعة', 0.08),
  ('سماعات', 'سماعة', 0.07),
  ('شاحن', 'شاحنة', 0.06),
  ('iphone', 'ايفون', 0.10),
  ('ipad', 'ايباد', 0.10),
  ('airpods', 'ايربودز', 0.10),
  ('ps5', 'بلايستيشن 5', 0.10),
  ('playstation 5', 'بلايستيشن 5', 0.10)
ON CONFLICT (alias, canonical) DO NOTHING;

-- 2) Seed brand aliases
INSERT INTO public.search_brand_aliases (alias, boost) VALUES
  ('apple', 0.11), ('ابل', 0.11),
  ('samsung', 0.10), ('سامسونج', 0.10),
  ('xiaomi', 0.09), ('شاومي', 0.09),
  ('huawei', 0.08), ('هواوي', 0.08),
  ('sony', 0.09), ('سوني', 0.09),
  ('lg', 0.07), ('hp', 0.07), ('dell', 0.07),
  ('lenovo', 0.07), ('asus', 0.07), ('acer', 0.07),
  ('anker', 0.07), ('tp-link', 0.06)
ON CONFLICT DO NOTHING;

-- 3) expand_query_text helper
CREATE OR REPLACE FUNCTION public.expand_query_text(p_query text)
RETURNS text
LANGUAGE sql STABLE
SET search_path TO 'public'
AS $$
WITH q AS (
  SELECT public.normalize_ar_text(coalesce(p_query,'')) AS qn
),
syn AS (
  SELECT string_agg(DISTINCT public.normalize_ar_text(s.canonical), ' ') AS canon
  FROM public.search_synonyms s CROSS JOIN q
  WHERE s.is_active = true
    AND q.qn LIKE '%' || public.normalize_ar_text(s.alias) || '%'
)
SELECT trim((SELECT qn FROM q) || ' ' || coalesce((SELECT canon FROM syn), ''));
$$;

-- 4) Trigram indexes
CREATE INDEX IF NOT EXISTS idx_products_name_ar_trgm
  ON public.products USING gin (public.normalize_ar_text(coalesce(name_ar,'')) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_products_name_en_trgm
  ON public.products USING gin (lower(coalesce(name_en,'')) gin_trgm_ops);

-- 5) Replace search_products_live with quality tuning
CREATE OR REPLACE FUNCTION public.search_products_live(
  p_query text,
  p_region_id uuid DEFAULT NULL,
  p_filters jsonb DEFAULT '{}'::jsonb,
  p_limit int DEFAULT 24,
  p_offset int DEFAULT 0,
  p_sort text DEFAULT 'best'
)
RETURNS TABLE(
  product_id uuid, name_ar text, name_en text, image_url text,
  category text, best_price_iqd numeric, source_id uuid,
  source_name text, rank_score numeric
)
LANGUAGE sql STABLE
SET search_path TO 'public', 'extensions'
AS $function$
WITH prm AS (
  SELECT
    public.normalize_ar_text(coalesce(p_query,'')) AS q,
    public.expand_query_text(coalesce(p_query,'')) AS qx,
    lower(coalesce(p_query,'')) AS q_en,
    coalesce(nullif(trim(coalesce(p_filters->>'category','')), ''), '') AS cat,
    coalesce(nullif(regexp_replace(coalesce(p_filters->>'min_price_iqd',''),'[^0-9.]','','g'),'')::numeric, 0) AS pmin,
    coalesce(nullif(regexp_replace(coalesce(p_filters->>'max_price_iqd',''),'[^0-9.]','','g'),'')::numeric, 999999999) AS pmax
),
offers AS (
  SELECT DISTINCT ON (o.product_id)
    o.product_id,
    o.normalized_price_iqd::numeric AS best_price_iqd,
    o.source_id,
    coalesce(o.merchant_name, ps.name_ar, ps.domain) AS source_name
  FROM public.source_price_observations o
  LEFT JOIN public.price_sources ps ON ps.id = o.source_id
  WHERE o.is_synthetic = false
    AND o.normalized_price_iqd > 0
    AND o.observed_at >= now() - interval '14 days'
    AND (p_region_id IS NULL OR o.region_id = p_region_id)
  ORDER BY o.product_id, o.normalized_price_iqd ASC, o.observed_at DESC
),
query_brands AS (
  SELECT b.alias, b.boost
  FROM public.search_brand_aliases b CROSS JOIN prm
  WHERE b.is_active = true
    AND (prm.q LIKE '%' || public.normalize_ar_text(b.alias) || '%'
      OR prm.q_en LIKE '%' || lower(b.alias) || '%')
),
prod AS (
  SELECT p.id, p.name_ar, p.name_en, p.image_url, p.category,
    public.normalize_ar_text(coalesce(p.name_ar,'')) AS ar_norm,
    lower(coalesce(p.name_en,'')) AS en_norm
  FROM public.products p WHERE p.is_active = true
),
cand AS (
  SELECT
    p.id AS product_id, p.name_ar, p.name_en, p.image_url, p.category,
    ofr.best_price_iqd, ofr.source_id, ofr.source_name,
    (
      GREATEST(
        extensions.similarity(p.ar_norm, prm.q),
        extensions.word_similarity(p.ar_norm, prm.q),
        CASE WHEN prm.qx <> prm.q THEN extensions.similarity(p.ar_norm, prm.qx) ELSE 0 END
      ) * 0.50
      + GREATEST(
          extensions.similarity(p.en_norm, prm.q_en),
          extensions.word_similarity(p.en_norm, prm.q_en)
        ) * 0.18
      + CASE WHEN p.ar_norm = prm.q OR p.en_norm = prm.q_en THEN 0.42 ELSE 0 END
      + CASE WHEN p.ar_norm LIKE prm.q || '%' OR p.en_norm LIKE prm.q_en || '%' THEN 0.24 ELSE 0 END
      + coalesce(br.brand_boost, 0)
      + CASE WHEN ofr.best_price_iqd IS NULL THEN 0
             ELSE LEAST(0.20, (30000.0 / NULLIF(ofr.best_price_iqd, 0))) END
    )::numeric(12,6) AS rank_score
  FROM prod p
  CROSS JOIN prm
  LEFT JOIN offers ofr ON ofr.product_id = p.id
  LEFT JOIN LATERAL (
    SELECT coalesce(max(qb.boost), 0)::numeric(8,4) AS brand_boost
    FROM query_brands qb
    WHERE p.ar_norm LIKE '%' || public.normalize_ar_text(qb.alias) || '%'
       OR p.en_norm LIKE '%' || lower(qb.alias) || '%'
  ) br ON true
  WHERE
    (p.ar_norm LIKE '%' || prm.q || '%'
      OR p.en_norm LIKE '%' || prm.q_en || '%'
      OR extensions.word_similarity(p.ar_norm, prm.q) >= 0.08
      OR extensions.word_similarity(p.en_norm, prm.q_en) >= 0.08
      OR (prm.qx <> prm.q AND (
        p.ar_norm LIKE '%' || prm.qx || '%'
        OR extensions.word_similarity(p.ar_norm, prm.qx) >= 0.08
      )))
    AND (prm.cat = '' OR coalesce(p.category,'') = prm.cat)
    AND coalesce(ofr.best_price_iqd, 0) BETWEEN prm.pmin AND prm.pmax
)
SELECT c.product_id, c.name_ar, c.name_en, c.image_url, c.category,
  c.best_price_iqd, c.source_id, c.source_name, c.rank_score
FROM cand c
ORDER BY
  CASE WHEN p_sort='price_asc'  THEN c.best_price_iqd END ASC NULLS LAST,
  CASE WHEN p_sort='price_desc' THEN c.best_price_iqd END DESC NULLS LAST,
  c.rank_score DESC, c.best_price_iqd ASC NULLS LAST
LIMIT GREATEST(1, LEAST(p_limit, 100))
OFFSET GREATEST(0, p_offset);
$function$;

-- 6) Update engine to pass original query text (for brand/synonym detection)
CREATE OR REPLACE FUNCTION public.search_products_engine(
  p_query text,
  p_region_id uuid DEFAULT NULL,
  p_filters jsonb DEFAULT '{}'::jsonb,
  p_limit int DEFAULT 24,
  p_offset int DEFAULT 0,
  p_sort text DEFAULT 'best'
)
RETURNS TABLE(
  query_id uuid, product_id uuid, name_ar text, name_en text,
  image_url text, category text, best_price_iqd numeric,
  source_name text, rank_score numeric, cache_hit boolean
)
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_started timestamptz := clock_timestamp();
  v_q_norm text; v_ckey text; v_qid uuid; v_exp timestamptz;
  v_rows int := 0; v_lat numeric; v_hit boolean := true; v_rid text;
BEGIN
  v_q_norm := normalize_ar_text(p_query);
  IF char_length(v_q_norm) < 2 THEN RETURN; END IF;

  v_ckey := search_cache_key(v_q_norm, p_region_id, p_filters);
  v_rid  := coalesce(p_region_id::text, '');

  SELECT q.id, q.expires_at INTO v_qid, v_exp
  FROM search_queries q WHERE q.query_key = v_ckey LIMIT 1;

  IF v_qid IS NULL THEN
    INSERT INTO search_queries (query_key, query_text, normalized_query, filters, status, expires_at, hits_count, last_executed_at)
    VALUES (v_ckey, p_query, v_q_norm, coalesce(p_filters,'{}'::jsonb), 'refreshing', now()-interval '1 second', 0, now())
    RETURNING id, expires_at INTO v_qid, v_exp;
  END IF;

  IF v_exp <= now() THEN
    v_hit := false;
    PERFORM pg_advisory_xact_lock(hashtext(v_ckey));
    SELECT q.expires_at INTO v_exp FROM search_queries q WHERE q.id = v_qid FOR UPDATE;

    IF v_exp <= now() THEN
      UPDATE search_queries SET status='refreshing', updated_at=now(), last_executed_at=now() WHERE id = v_qid;
      DELETE FROM search_cache_entries WHERE query_id = v_qid AND region_id = v_rid;

      INSERT INTO search_cache_entries (query_id, product_id, region_id, rank, rank_score, best_price_iqd, source_id, source_name, image_url, payload)
      SELECT v_qid, l.product_id, v_rid,
        row_number() OVER (ORDER BY l.rank_score DESC, l.best_price_iqd ASC NULLS LAST)::int,
        l.rank_score, l.best_price_iqd, l.source_id, l.source_name, l.image_url,
        jsonb_build_object('name_ar',l.name_ar,'name_en',l.name_en,'category',l.category)
      FROM search_products_live(p_query, p_region_id, p_filters, GREATEST((p_limit + p_offset) * 4, 120), 0, 'best') l
      ON CONFLICT (query_id, product_id, region_id) DO UPDATE SET
        rank_score=EXCLUDED.rank_score, best_price_iqd=EXCLUDED.best_price_iqd,
        source_id=EXCLUDED.source_id, source_name=EXCLUDED.source_name,
        image_url=EXCLUDED.image_url, payload=EXCLUDED.payload, updated_at=now();

      GET DIAGNOSTICS v_rows = ROW_COUNT;
      UPDATE search_queries SET status='ready', result_count=v_rows, expires_at=now()+interval '6 hours',
        hits_count=hits_count+1, updated_at=now(), last_executed_at=now() WHERE id = v_qid;
    END IF;
  ELSE
    UPDATE search_queries SET hits_count=hits_count+1, last_executed_at=now(), updated_at=now() WHERE id = v_qid;
  END IF;

  v_lat := round((extract(epoch FROM clock_timestamp()-v_started)*1000)::numeric, 2);
  UPDATE search_queries SET avg_latency_ms = CASE WHEN avg_latency_ms IS NULL THEN v_lat
    ELSE round((avg_latency_ms*0.70+v_lat*0.30)::numeric,2) END, updated_at=now() WHERE id = v_qid;

  INSERT INTO search_query_events (query_id, cache_hit, latency_ms, result_count)
  VALUES (v_qid, v_hit, v_lat,
    COALESCE(NULLIF(v_rows, 0),
      (SELECT count(*)::int FROM search_cache_entries WHERE query_id = v_qid AND region_id = v_rid)));

  RETURN QUERY
  SELECT v_qid, c.product_id, p.name_ar, p.name_en,
    coalesce(nullif(c.image_url,''), p.image_url), p.category, c.best_price_iqd,
    c.source_name, c.rank_score, v_hit
  FROM search_cache_entries c JOIN products p ON p.id = c.product_id
  WHERE c.query_id = v_qid AND c.region_id = v_rid
  ORDER BY
    CASE WHEN p_sort='price_asc' THEN c.best_price_iqd END ASC NULLS LAST,
    CASE WHEN p_sort='price_desc' THEN c.best_price_iqd END DESC NULLS LAST,
    c.rank_score DESC, c.best_price_iqd ASC NULLS LAST
  LIMIT GREATEST(1,LEAST(p_limit,100)) OFFSET GREATEST(0,p_offset);

EXCEPTION WHEN OTHERS THEN
  UPDATE search_queries SET status='failed', updated_at=now() WHERE id=v_qid;
  RAISE;
END;
$function$;

-- 7) Expire existing cache so next searches rebuild with new ranking
UPDATE public.search_queries
SET expires_at = now() - interval '1 second', updated_at = now()
WHERE expires_at > now();
